{{- if .Values.ingress.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.frontend.className }}
  {{- if .Values.ingress.frontend.tls.enabled }}
  tls:
  - hosts:
    {{- range .Values.ingress.frontend.tls.hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .Values.ingress.frontend.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.frontend.host }}
    http:
      paths:
      {{- range .Values.ingress.frontend.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .service.name }}
            port:
              number: {{ .service.port }}
      {{- end }}
{{- end }}
